import type { Locale } from "../../../../i18n/locales";
import { getLocalizedAdministrativeAreaLabel } from "./accountAdministrativeAreaLabels";

export const countryCodes = [
  "AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW", "AU", "AT", "AZ",
  "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BQ", "BA", "BW", "BV", "BR",
  "IO", "BN", "BG", "BF", "BI", "CV", "KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC",
  "CO", "KM", "CG", "CD", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ", "DK", "DJ", "DM", "DO",
  "EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF",
  "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY",
  "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM",
  "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY",
  "LI", "LT", "LU", "MO", "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX",
  "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "NC", "NZ", "NI",
  "NE", "NG", "NU", "NF", "MK", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH",
  "PN", "PL", "PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC",
  "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "GS",
  "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK",
  "TO", "TT", "TN", "TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "US", "UM", "UY", "UZ", "VU",
  "VE", "VN", "VG", "VI", "WF", "EH", "YE", "ZM", "ZW",
] as const;

export type CountryCodeOption = typeof countryCodes[number];

type AdministrativeAreaOption = {
  code: string;
  countryCode: CountryCodeOption;
  enumName: string;
};

const administrativeAreaOptions = [
  { countryCode: "JP", code: "01", enumName: "JAPAN_HOKKAIDO" },
  { countryCode: "JP", code: "02", enumName: "JAPAN_AOMORI" },
  { countryCode: "JP", code: "03", enumName: "JAPAN_IWATE" },
  { countryCode: "JP", code: "04", enumName: "JAPAN_MIYAGI" },
  { countryCode: "JP", code: "05", enumName: "JAPAN_AKITA" },
  { countryCode: "JP", code: "06", enumName: "JAPAN_YAMAGATA" },
  { countryCode: "JP", code: "07", enumName: "JAPAN_FUKUSHIMA" },
  { countryCode: "JP", code: "08", enumName: "JAPAN_IBARAKI" },
  { countryCode: "JP", code: "09", enumName: "JAPAN_TOCHIGI" },
  { countryCode: "JP", code: "10", enumName: "JAPAN_GUNMA" },
  { countryCode: "JP", code: "11", enumName: "JAPAN_SAITAMA" },
  { countryCode: "JP", code: "12", enumName: "JAPAN_CHIBA" },
  { countryCode: "JP", code: "13", enumName: "JAPAN_TOKYO" },
  { countryCode: "JP", code: "14", enumName: "JAPAN_KANAGAWA" },
  { countryCode: "JP", code: "15", enumName: "JAPAN_NIIGATA" },
  { countryCode: "JP", code: "16", enumName: "JAPAN_TOYAMA" },
  { countryCode: "JP", code: "17", enumName: "JAPAN_ISHIKAWA" },
  { countryCode: "JP", code: "18", enumName: "JAPAN_FUKUI" },
  { countryCode: "JP", code: "19", enumName: "JAPAN_YAMANASHI" },
  { countryCode: "JP", code: "20", enumName: "JAPAN_NAGANO" },
  { countryCode: "JP", code: "21", enumName: "JAPAN_GIFU" },
  { countryCode: "JP", code: "22", enumName: "JAPAN_SHIZUOKA" },
  { countryCode: "JP", code: "23", enumName: "JAPAN_AICHI" },
  { countryCode: "JP", code: "24", enumName: "JAPAN_MIE" },
  { countryCode: "JP", code: "25", enumName: "JAPAN_SHIGA" },
  { countryCode: "JP", code: "26", enumName: "JAPAN_KYOTO" },
  { countryCode: "JP", code: "27", enumName: "JAPAN_OSAKA" },
  { countryCode: "JP", code: "28", enumName: "JAPAN_HYOGO" },
  { countryCode: "JP", code: "29", enumName: "JAPAN_NARA" },
  { countryCode: "JP", code: "30", enumName: "JAPAN_WAKAYAMA" },
  { countryCode: "JP", code: "31", enumName: "JAPAN_TOTTORI" },
  { countryCode: "JP", code: "32", enumName: "JAPAN_SHIMANE" },
  { countryCode: "JP", code: "33", enumName: "JAPAN_OKAYAMA" },
  { countryCode: "JP", code: "34", enumName: "JAPAN_HIROSHIMA" },
  { countryCode: "JP", code: "35", enumName: "JAPAN_YAMAGUCHI" },
  { countryCode: "JP", code: "36", enumName: "JAPAN_TOKUSHIMA" },
  { countryCode: "JP", code: "37", enumName: "JAPAN_KAGAWA" },
  { countryCode: "JP", code: "38", enumName: "JAPAN_EHIME" },
  { countryCode: "JP", code: "39", enumName: "JAPAN_KOCHI" },
  { countryCode: "JP", code: "40", enumName: "JAPAN_FUKUOKA" },
  { countryCode: "JP", code: "41", enumName: "JAPAN_SAGA" },
  { countryCode: "JP", code: "42", enumName: "JAPAN_NAGASAKI" },
  { countryCode: "JP", code: "43", enumName: "JAPAN_KUMAMOTO" },
  { countryCode: "JP", code: "44", enumName: "JAPAN_OITA" },
  { countryCode: "JP", code: "45", enumName: "JAPAN_MIYAZAKI" },
  { countryCode: "JP", code: "46", enumName: "JAPAN_KAGOSHIMA" },
  { countryCode: "JP", code: "47", enumName: "JAPAN_OKINAWA" },
  { countryCode: "KR", code: "11", enumName: "KOREA_SEOUL" },
  { countryCode: "KR", code: "26", enumName: "KOREA_BUSAN" },
  { countryCode: "KR", code: "27", enumName: "KOREA_DAEGU" },
  { countryCode: "KR", code: "28", enumName: "KOREA_INCHEON" },
  { countryCode: "KR", code: "29", enumName: "KOREA_GWANGJU" },
  { countryCode: "KR", code: "30", enumName: "KOREA_DAEJEON" },
  { countryCode: "KR", code: "31", enumName: "KOREA_ULSAN" },
  { countryCode: "KR", code: "41", enumName: "KOREA_GYEONGGI" },
  { countryCode: "KR", code: "42", enumName: "KOREA_GANGWON" },
  { countryCode: "KR", code: "43", enumName: "KOREA_CHUNGCHEONGBUK" },
  { countryCode: "KR", code: "44", enumName: "KOREA_CHUNGCHEONGNAM" },
  { countryCode: "KR", code: "45", enumName: "KOREA_JEOLLABUK" },
  { countryCode: "KR", code: "46", enumName: "KOREA_JEOLLANAM" },
  { countryCode: "KR", code: "47", enumName: "KOREA_GYEONGSANGBUK" },
  { countryCode: "KR", code: "48", enumName: "KOREA_GYEONGSANGNAM" },
  { countryCode: "KR", code: "49", enumName: "KOREA_JEJU" },
  { countryCode: "KR", code: "50", enumName: "KOREA_SEJONG" },
  { countryCode: "US", code: "AL", enumName: "UNITED_STATES_ALABAMA" },
  { countryCode: "US", code: "AK", enumName: "UNITED_STATES_ALASKA" },
  { countryCode: "US", code: "AZ", enumName: "UNITED_STATES_ARIZONA" },
  { countryCode: "US", code: "AR", enumName: "UNITED_STATES_ARKANSAS" },
  { countryCode: "US", code: "CA", enumName: "UNITED_STATES_CALIFORNIA" },
  { countryCode: "US", code: "CO", enumName: "UNITED_STATES_COLORADO" },
  { countryCode: "US", code: "CT", enumName: "UNITED_STATES_CONNECTICUT" },
  { countryCode: "US", code: "DE", enumName: "UNITED_STATES_DELAWARE" },
  { countryCode: "US", code: "DC", enumName: "UNITED_STATES_DISTRICT_OF_COLUMBIA" },
  { countryCode: "US", code: "FL", enumName: "UNITED_STATES_FLORIDA" },
  { countryCode: "US", code: "GA", enumName: "UNITED_STATES_GEORGIA" },
  { countryCode: "US", code: "HI", enumName: "UNITED_STATES_HAWAII" },
  { countryCode: "US", code: "ID", enumName: "UNITED_STATES_IDAHO" },
  { countryCode: "US", code: "IL", enumName: "UNITED_STATES_ILLINOIS" },
  { countryCode: "US", code: "IN", enumName: "UNITED_STATES_INDIANA" },
  { countryCode: "US", code: "IA", enumName: "UNITED_STATES_IOWA" },
  { countryCode: "US", code: "KS", enumName: "UNITED_STATES_KANSAS" },
  { countryCode: "US", code: "KY", enumName: "UNITED_STATES_KENTUCKY" },
  { countryCode: "US", code: "LA", enumName: "UNITED_STATES_LOUISIANA" },
  { countryCode: "US", code: "ME", enumName: "UNITED_STATES_MAINE" },
  { countryCode: "US", code: "MD", enumName: "UNITED_STATES_MARYLAND" },
  { countryCode: "US", code: "MA", enumName: "UNITED_STATES_MASSACHUSETTS" },
  { countryCode: "US", code: "MI", enumName: "UNITED_STATES_MICHIGAN" },
  { countryCode: "US", code: "MN", enumName: "UNITED_STATES_MINNESOTA" },
  { countryCode: "US", code: "MS", enumName: "UNITED_STATES_MISSISSIPPI" },
  { countryCode: "US", code: "MO", enumName: "UNITED_STATES_MISSOURI" },
  { countryCode: "US", code: "MT", enumName: "UNITED_STATES_MONTANA" },
  { countryCode: "US", code: "NE", enumName: "UNITED_STATES_NEBRASKA" },
  { countryCode: "US", code: "NV", enumName: "UNITED_STATES_NEVADA" },
  { countryCode: "US", code: "NH", enumName: "UNITED_STATES_NEW_HAMPSHIRE" },
  { countryCode: "US", code: "NJ", enumName: "UNITED_STATES_NEW_JERSEY" },
  { countryCode: "US", code: "NM", enumName: "UNITED_STATES_NEW_MEXICO" },
  { countryCode: "US", code: "NY", enumName: "UNITED_STATES_NEW_YORK" },
  { countryCode: "US", code: "NC", enumName: "UNITED_STATES_NORTH_CAROLINA" },
  { countryCode: "US", code: "ND", enumName: "UNITED_STATES_NORTH_DAKOTA" },
  { countryCode: "US", code: "OH", enumName: "UNITED_STATES_OHIO" },
  { countryCode: "US", code: "OK", enumName: "UNITED_STATES_OKLAHOMA" },
  { countryCode: "US", code: "OR", enumName: "UNITED_STATES_OREGON" },
  { countryCode: "US", code: "PA", enumName: "UNITED_STATES_PENNSYLVANIA" },
  { countryCode: "US", code: "RI", enumName: "UNITED_STATES_RHODE_ISLAND" },
  { countryCode: "US", code: "SC", enumName: "UNITED_STATES_SOUTH_CAROLINA" },
  { countryCode: "US", code: "SD", enumName: "UNITED_STATES_SOUTH_DAKOTA" },
  { countryCode: "US", code: "TN", enumName: "UNITED_STATES_TENNESSEE" },
  { countryCode: "US", code: "TX", enumName: "UNITED_STATES_TEXAS" },
  { countryCode: "US", code: "UT", enumName: "UNITED_STATES_UTAH" },
  { countryCode: "US", code: "VT", enumName: "UNITED_STATES_VERMONT" },
  { countryCode: "US", code: "VA", enumName: "UNITED_STATES_VIRGINIA" },
  { countryCode: "US", code: "WA", enumName: "UNITED_STATES_WASHINGTON" },
  { countryCode: "US", code: "WV", enumName: "UNITED_STATES_WEST_VIRGINIA" },
  { countryCode: "US", code: "WI", enumName: "UNITED_STATES_WISCONSIN" },
  { countryCode: "US", code: "WY", enumName: "UNITED_STATES_WYOMING" },
  { countryCode: "AU", code: "NSW", enumName: "AUSTRALIA_NEW_SOUTH_WALES" },
  { countryCode: "AU", code: "VIC", enumName: "AUSTRALIA_VICTORIA" },
  { countryCode: "AU", code: "QLD", enumName: "AUSTRALIA_QUEENSLAND" },
  { countryCode: "AU", code: "WA", enumName: "AUSTRALIA_WESTERN_AUSTRALIA" },
  { countryCode: "AU", code: "SA", enumName: "AUSTRALIA_SOUTH_AUSTRALIA" },
  { countryCode: "AU", code: "TAS", enumName: "AUSTRALIA_TASMANIA" },
  { countryCode: "AU", code: "ACT", enumName: "AUSTRALIA_AUSTRALIAN_CAPITAL_TERRITORY" },
  { countryCode: "AU", code: "NT", enumName: "AUSTRALIA_NORTHERN_TERRITORY" },
  { countryCode: "CA", code: "AB", enumName: "CANADA_ALBERTA" },
  { countryCode: "CA", code: "BC", enumName: "CANADA_BRITISH_COLUMBIA" },
  { countryCode: "CA", code: "MB", enumName: "CANADA_MANITOBA" },
  { countryCode: "CA", code: "NB", enumName: "CANADA_NEW_BRUNSWICK" },
  { countryCode: "CA", code: "NL", enumName: "CANADA_NEWFOUNDLAND_AND_LABRADOR" },
  { countryCode: "CA", code: "NS", enumName: "CANADA_NOVA_SCOTIA" },
  { countryCode: "CA", code: "NT", enumName: "CANADA_NORTHWEST_TERRITORIES" },
  { countryCode: "CA", code: "NU", enumName: "CANADA_NUNAVUT" },
  { countryCode: "CA", code: "ON", enumName: "CANADA_ONTARIO" },
  { countryCode: "CA", code: "PE", enumName: "CANADA_PRINCE_EDWARD_ISLAND" },
  { countryCode: "CA", code: "QC", enumName: "CANADA_QUEBEC" },
  { countryCode: "CA", code: "SK", enumName: "CANADA_SASKATCHEWAN" },
  { countryCode: "CA", code: "YT", enumName: "CANADA_YUKON" },
  { countryCode: "NZ", code: "AUK", enumName: "NEW_ZEALAND_AUCKLAND" },
  { countryCode: "NZ", code: "BOP", enumName: "NEW_ZEALAND_BAY_OF_PLENTY" },
  { countryCode: "NZ", code: "CAN", enumName: "NEW_ZEALAND_CANTERBURY" },
  { countryCode: "NZ", code: "GIS", enumName: "NEW_ZEALAND_GISBORNE" },
  { countryCode: "NZ", code: "HKB", enumName: "NEW_ZEALAND_HAWKES_BAY" },
  { countryCode: "NZ", code: "MBH", enumName: "NEW_ZEALAND_MARLBOROUGH" },
  { countryCode: "NZ", code: "MWT", enumName: "NEW_ZEALAND_MANAWATU_WANGANUI" },
  { countryCode: "NZ", code: "NSN", enumName: "NEW_ZEALAND_NELSON" },
  { countryCode: "NZ", code: "NTL", enumName: "NEW_ZEALAND_NORTHLAND" },
  { countryCode: "NZ", code: "OTA", enumName: "NEW_ZEALAND_OTAGO" },
  { countryCode: "NZ", code: "STL", enumName: "NEW_ZEALAND_SOUTHLAND" },
  { countryCode: "NZ", code: "TKI", enumName: "NEW_ZEALAND_TARANAKI" },
  { countryCode: "NZ", code: "TAS", enumName: "NEW_ZEALAND_TASMAN" },
  { countryCode: "NZ", code: "WKO", enumName: "NEW_ZEALAND_WAIKATO" },
  { countryCode: "NZ", code: "WGN", enumName: "NEW_ZEALAND_WELLINGTON" },
  { countryCode: "NZ", code: "WTC", enumName: "NEW_ZEALAND_WEST_COAST" },
  { countryCode: "CN", code: "11", enumName: "CHINA_BEIJING" },
  { countryCode: "CN", code: "12", enumName: "CHINA_TIANJIN" },
  { countryCode: "CN", code: "13", enumName: "CHINA_HEBEI" },
  { countryCode: "CN", code: "14", enumName: "CHINA_SHANXI" },
  { countryCode: "CN", code: "15", enumName: "CHINA_INNER_MONGOLIA" },
  { countryCode: "CN", code: "21", enumName: "CHINA_LIAONING" },
  { countryCode: "CN", code: "22", enumName: "CHINA_JILIN" },
  { countryCode: "CN", code: "23", enumName: "CHINA_HEILONGJIANG" },
  { countryCode: "CN", code: "31", enumName: "CHINA_SHANGHAI" },
  { countryCode: "CN", code: "32", enumName: "CHINA_JIANGSU" },
  { countryCode: "CN", code: "33", enumName: "CHINA_ZHEJIANG" },
  { countryCode: "CN", code: "34", enumName: "CHINA_ANHUI" },
  { countryCode: "CN", code: "35", enumName: "CHINA_FUJIAN" },
  { countryCode: "CN", code: "36", enumName: "CHINA_JIANGXI" },
  { countryCode: "CN", code: "37", enumName: "CHINA_SHANDONG" },
  { countryCode: "CN", code: "41", enumName: "CHINA_HENAN" },
  { countryCode: "CN", code: "42", enumName: "CHINA_HUBEI" },
  { countryCode: "CN", code: "43", enumName: "CHINA_HUNAN" },
  { countryCode: "CN", code: "44", enumName: "CHINA_GUANGDONG" },
  { countryCode: "CN", code: "45", enumName: "CHINA_GUANGXI" },
  { countryCode: "CN", code: "46", enumName: "CHINA_HAINAN" },
  { countryCode: "CN", code: "50", enumName: "CHINA_CHONGQING" },
  { countryCode: "CN", code: "51", enumName: "CHINA_SICHUAN" },
  { countryCode: "CN", code: "52", enumName: "CHINA_GUIZHOU" },
  { countryCode: "CN", code: "53", enumName: "CHINA_YUNNAN" },
  { countryCode: "CN", code: "54", enumName: "CHINA_XIZANG" },
  { countryCode: "CN", code: "61", enumName: "CHINA_SHAANXI" },
  { countryCode: "CN", code: "62", enumName: "CHINA_GANSU" },
  { countryCode: "CN", code: "63", enumName: "CHINA_QINGHAI" },
  { countryCode: "CN", code: "64", enumName: "CHINA_NINGXIA" },
  { countryCode: "CN", code: "65", enumName: "CHINA_XINJIANG" },
  { countryCode: "CN", code: "71", enumName: "CHINA_TAIWAN" },
  { countryCode: "CN", code: "91", enumName: "CHINA_HONG_KONG" },
  { countryCode: "CN", code: "92", enumName: "CHINA_MACAO" },
  { countryCode: "TW", code: "TPE", enumName: "TAIWAN_TAIPEI" },
  { countryCode: "TW", code: "NWT", enumName: "TAIWAN_NEW_TAIPEI" },
  { countryCode: "TW", code: "TAO", enumName: "TAIWAN_TAOYUAN" },
  { countryCode: "TW", code: "TXG", enumName: "TAIWAN_TAICHUNG" },
  { countryCode: "TW", code: "TNN", enumName: "TAIWAN_TAINAN" },
  { countryCode: "TW", code: "KHH", enumName: "TAIWAN_KAOHSIUNG" },
  { countryCode: "TW", code: "HSZ", enumName: "TAIWAN_HSINCHU_CITY" },
  { countryCode: "TW", code: "HSQ", enumName: "TAIWAN_HSINCHU_COUNTY" },
  { countryCode: "TW", code: "MIA", enumName: "TAIWAN_MIAOLI" },
  { countryCode: "TW", code: "CHA", enumName: "TAIWAN_CHANGHUA" },
  { countryCode: "TW", code: "NAN", enumName: "TAIWAN_NANTOU" },
  { countryCode: "TW", code: "YUN", enumName: "TAIWAN_YUNLIN" },
  { countryCode: "TW", code: "CYI", enumName: "TAIWAN_CHIAYI_CITY" },
  { countryCode: "TW", code: "CYQ", enumName: "TAIWAN_CHIAYI_COUNTY" },
  { countryCode: "TW", code: "PIF", enumName: "TAIWAN_PINGTUNG" },
  { countryCode: "TW", code: "ILA", enumName: "TAIWAN_YILAN" },
  { countryCode: "TW", code: "HUA", enumName: "TAIWAN_HUALIEN" },
  { countryCode: "TW", code: "TTT", enumName: "TAIWAN_TAITUNG" },
  { countryCode: "TW", code: "PEN", enumName: "TAIWAN_PENGHU" },
  { countryCode: "TW", code: "KIN", enumName: "TAIWAN_KINMEN" },
  { countryCode: "TW", code: "LIE", enumName: "TAIWAN_LIENCHIANG" },
  { countryCode: "TH", code: "10", enumName: "THAILAND_BANGKOK" },
  { countryCode: "TH", code: "11", enumName: "THAILAND_SAMUT_PRAKAN" },
  { countryCode: "TH", code: "12", enumName: "THAILAND_NONTHABURI" },
  { countryCode: "TH", code: "13", enumName: "THAILAND_PATHUM_THANI" },
  { countryCode: "TH", code: "14", enumName: "THAILAND_PHRA_NAKHON_SI_AYUTTHAYA" },
  { countryCode: "TH", code: "15", enumName: "THAILAND_ANG_THONG" },
  { countryCode: "TH", code: "16", enumName: "THAILAND_LOP_BURI" },
  { countryCode: "TH", code: "17", enumName: "THAILAND_SING_BURI" },
  { countryCode: "TH", code: "18", enumName: "THAILAND_CHAI_NAT" },
  { countryCode: "TH", code: "19", enumName: "THAILAND_SARABURI" },
  { countryCode: "TH", code: "20", enumName: "THAILAND_CHON_BURI" },
  { countryCode: "TH", code: "21", enumName: "THAILAND_RAYONG" },
  { countryCode: "TH", code: "22", enumName: "THAILAND_CHANTHABURI" },
  { countryCode: "TH", code: "23", enumName: "THAILAND_TRAT" },
  { countryCode: "TH", code: "24", enumName: "THAILAND_CHACHOENGSAO" },
  { countryCode: "TH", code: "25", enumName: "THAILAND_PRACHIN_BURI" },
  { countryCode: "TH", code: "26", enumName: "THAILAND_NAKHON_NAYOK" },
  { countryCode: "TH", code: "27", enumName: "THAILAND_SA_KAEO" },
  { countryCode: "TH", code: "30", enumName: "THAILAND_NAKHON_RATCHASIMA" },
  { countryCode: "TH", code: "31", enumName: "THAILAND_BURI_RAM" },
  { countryCode: "TH", code: "32", enumName: "THAILAND_SURIN" },
  { countryCode: "TH", code: "33", enumName: "THAILAND_SI_SA_KET" },
  { countryCode: "TH", code: "34", enumName: "THAILAND_UBON_RATCHATHANI" },
  { countryCode: "TH", code: "35", enumName: "THAILAND_YASOTHON" },
  { countryCode: "TH", code: "36", enumName: "THAILAND_CHAIYAPHUM" },
  { countryCode: "TH", code: "37", enumName: "THAILAND_AMNAT_CHAROEN" },
  { countryCode: "TH", code: "38", enumName: "THAILAND_BUENG_KAN" },
  { countryCode: "TH", code: "39", enumName: "THAILAND_NONG_BUA_LAM_PHU" },
  { countryCode: "TH", code: "40", enumName: "THAILAND_KHON_KAEN" },
  { countryCode: "TH", code: "41", enumName: "THAILAND_UDON_THANI" },
  { countryCode: "TH", code: "42", enumName: "THAILAND_LOEI" },
  { countryCode: "TH", code: "43", enumName: "THAILAND_NONG_KHAI" },
  { countryCode: "TH", code: "44", enumName: "THAILAND_MAHA_SARAKHAM" },
  { countryCode: "TH", code: "45", enumName: "THAILAND_ROI_ET" },
  { countryCode: "TH", code: "46", enumName: "THAILAND_KALASIN" },
  { countryCode: "TH", code: "47", enumName: "THAILAND_SAKON_NAKHON" },
  { countryCode: "TH", code: "48", enumName: "THAILAND_NAKHON_PHANOM" },
  { countryCode: "TH", code: "49", enumName: "THAILAND_MUKDAHAN" },
  { countryCode: "TH", code: "50", enumName: "THAILAND_CHIANG_MAI" },
  { countryCode: "TH", code: "51", enumName: "THAILAND_LAMPHUN" },
  { countryCode: "TH", code: "52", enumName: "THAILAND_LAMPANG" },
  { countryCode: "TH", code: "53", enumName: "THAILAND_UTTARADIT" },
  { countryCode: "TH", code: "54", enumName: "THAILAND_PHRAE" },
  { countryCode: "TH", code: "55", enumName: "THAILAND_NAN" },
  { countryCode: "TH", code: "56", enumName: "THAILAND_PHAYAO" },
  { countryCode: "TH", code: "57", enumName: "THAILAND_CHIANG_RAI" },
  { countryCode: "TH", code: "58", enumName: "THAILAND_MAE_HONG_SON" },
  { countryCode: "TH", code: "60", enumName: "THAILAND_NAKHON_SAWAN" },
  { countryCode: "TH", code: "61", enumName: "THAILAND_UTHAI_THANI" },
  { countryCode: "TH", code: "62", enumName: "THAILAND_KAMPHAENG_PHET" },
  { countryCode: "TH", code: "63", enumName: "THAILAND_TAK" },
  { countryCode: "TH", code: "64", enumName: "THAILAND_SUKHOTHAI" },
  { countryCode: "TH", code: "65", enumName: "THAILAND_PHITSANULOK" },
  { countryCode: "TH", code: "66", enumName: "THAILAND_PHICHIT" },
  { countryCode: "TH", code: "67", enumName: "THAILAND_PHETCHABUN" },
  { countryCode: "TH", code: "70", enumName: "THAILAND_RATCHABURI" },
  { countryCode: "TH", code: "71", enumName: "THAILAND_KANCHANABURI" },
  { countryCode: "TH", code: "72", enumName: "THAILAND_SUPHAN_BURI" },
  { countryCode: "TH", code: "73", enumName: "THAILAND_NAKHON_PATHOM" },
  { countryCode: "TH", code: "74", enumName: "THAILAND_SAMUT_SAKHON" },
  { countryCode: "TH", code: "75", enumName: "THAILAND_SAMUT_SONGKHRAM" },
  { countryCode: "TH", code: "76", enumName: "THAILAND_PHETCHABURI" },
  { countryCode: "TH", code: "77", enumName: "THAILAND_PRACHUAP_KHIRI_KHAN" },
  { countryCode: "TH", code: "80", enumName: "THAILAND_NAKHON_SI_THAMMARAT" },
  { countryCode: "TH", code: "81", enumName: "THAILAND_KRABI" },
  { countryCode: "TH", code: "82", enumName: "THAILAND_PHANGNGA" },
  { countryCode: "TH", code: "83", enumName: "THAILAND_PHUKET" },
  { countryCode: "TH", code: "84", enumName: "THAILAND_SURAT_THANI" },
  { countryCode: "TH", code: "85", enumName: "THAILAND_RANONG" },
  { countryCode: "TH", code: "86", enumName: "THAILAND_CHUMPHON" },
  { countryCode: "TH", code: "90", enumName: "THAILAND_SONGKHLA" },
  { countryCode: "TH", code: "91", enumName: "THAILAND_SATUN" },
  { countryCode: "TH", code: "92", enumName: "THAILAND_TRANG" },
  { countryCode: "TH", code: "93", enumName: "THAILAND_PHATTHALUNG" },
  { countryCode: "TH", code: "94", enumName: "THAILAND_PATTANI" },
  { countryCode: "TH", code: "95", enumName: "THAILAND_YALA" },
  { countryCode: "TH", code: "96", enumName: "THAILAND_NARATHIWAT" },
  { countryCode: "TH", code: "S", enumName: "THAILAND_PHATTHAYA" },
  { countryCode: "PH", code: "00", enumName: "PHILIPPINES_NATIONAL_CAPITAL_REGION" },
  { countryCode: "PH", code: "01", enumName: "PHILIPPINES_ILOCOS" },
  { countryCode: "PH", code: "02", enumName: "PHILIPPINES_CAGAYAN_VALLEY" },
  { countryCode: "PH", code: "03", enumName: "PHILIPPINES_CENTRAL_LUZON" },
  { countryCode: "PH", code: "05", enumName: "PHILIPPINES_BICOL" },
  { countryCode: "PH", code: "06", enumName: "PHILIPPINES_WESTERN_VISAYAS" },
  { countryCode: "PH", code: "07", enumName: "PHILIPPINES_CENTRAL_VISAYAS" },
  { countryCode: "PH", code: "08", enumName: "PHILIPPINES_EASTERN_VISAYAS" },
  { countryCode: "PH", code: "09", enumName: "PHILIPPINES_ZAMBOANGA_PENINSULA" },
  { countryCode: "PH", code: "10", enumName: "PHILIPPINES_NORTHERN_MINDANAO" },
  { countryCode: "PH", code: "11", enumName: "PHILIPPINES_DAVAO" },
  { countryCode: "PH", code: "12", enumName: "PHILIPPINES_SOCCSKSARGEN" },
  { countryCode: "PH", code: "13", enumName: "PHILIPPINES_CARAGA" },
  { countryCode: "PH", code: "14", enumName: "PHILIPPINES_BANGSAMORO_AUTONOMOUS_REGION_IN_MUSLIM_MINDANAO" },
  { countryCode: "PH", code: "15", enumName: "PHILIPPINES_CORDILLERA_ADMINISTRATIVE_REGION" },
  { countryCode: "PH", code: "40", enumName: "PHILIPPINES_CALABARZON" },
  { countryCode: "PH", code: "41", enumName: "PHILIPPINES_MIMAROPA" },
  { countryCode: "PH", code: "ABR", enumName: "PHILIPPINES_ABRA" },
  { countryCode: "PH", code: "AGN", enumName: "PHILIPPINES_AGUSAN_DEL_NORTE" },
  { countryCode: "PH", code: "AGS", enumName: "PHILIPPINES_AGUSAN_DEL_SUR" },
  { countryCode: "PH", code: "AKL", enumName: "PHILIPPINES_AKLAN" },
  { countryCode: "PH", code: "ALB", enumName: "PHILIPPINES_ALBAY" },
  { countryCode: "PH", code: "ANT", enumName: "PHILIPPINES_ANTIQUE" },
  { countryCode: "PH", code: "APA", enumName: "PHILIPPINES_APAYAO" },
  { countryCode: "PH", code: "AUR", enumName: "PHILIPPINES_AURORA" },
  { countryCode: "PH", code: "BAN", enumName: "PHILIPPINES_BATAAN" },
  { countryCode: "PH", code: "BAS", enumName: "PHILIPPINES_BASILAN" },
  { countryCode: "PH", code: "BEN", enumName: "PHILIPPINES_BENGUET" },
  { countryCode: "PH", code: "BIL", enumName: "PHILIPPINES_BILIRAN" },
  { countryCode: "PH", code: "BOH", enumName: "PHILIPPINES_BOHOL" },
  { countryCode: "PH", code: "BTG", enumName: "PHILIPPINES_BATANGAS" },
  { countryCode: "PH", code: "BTN", enumName: "PHILIPPINES_BATANES" },
  { countryCode: "PH", code: "BUK", enumName: "PHILIPPINES_BUKIDNON" },
  { countryCode: "PH", code: "BUL", enumName: "PHILIPPINES_BULACAN" },
  { countryCode: "PH", code: "CAG", enumName: "PHILIPPINES_CAGAYAN" },
  { countryCode: "PH", code: "CAM", enumName: "PHILIPPINES_CAMIGUIN" },
  { countryCode: "PH", code: "CAN", enumName: "PHILIPPINES_CAMARINES_NORTE" },
  { countryCode: "PH", code: "CAP", enumName: "PHILIPPINES_CAPIZ" },
  { countryCode: "PH", code: "CAS", enumName: "PHILIPPINES_CAMARINES_SUR" },
  { countryCode: "PH", code: "CAT", enumName: "PHILIPPINES_CATANDUANES" },
  { countryCode: "PH", code: "CAV", enumName: "PHILIPPINES_CAVITE" },
  { countryCode: "PH", code: "CEB", enumName: "PHILIPPINES_CEBU" },
  { countryCode: "PH", code: "COM", enumName: "PHILIPPINES_DAVAO_DE_ORO" },
  { countryCode: "PH", code: "DAO", enumName: "PHILIPPINES_DAVAO_ORIENTAL" },
  { countryCode: "PH", code: "DAS", enumName: "PHILIPPINES_DAVAO_DEL_SUR" },
  { countryCode: "PH", code: "DAV", enumName: "PHILIPPINES_DAVAO_DEL_NORTE" },
  { countryCode: "PH", code: "DIN", enumName: "PHILIPPINES_DINAGAT_ISLANDS" },
  { countryCode: "PH", code: "DVO", enumName: "PHILIPPINES_DAVAO_OCCIDENTAL" },
  { countryCode: "PH", code: "EAS", enumName: "PHILIPPINES_EASTERN_SAMAR" },
  { countryCode: "PH", code: "GUI", enumName: "PHILIPPINES_GUIMARAS" },
  { countryCode: "PH", code: "IFU", enumName: "PHILIPPINES_IFUGAO" },
  { countryCode: "PH", code: "ILI", enumName: "PHILIPPINES_ILOILO" },
  { countryCode: "PH", code: "ILN", enumName: "PHILIPPINES_ILOCOS_NORTE" },
  { countryCode: "PH", code: "ILS", enumName: "PHILIPPINES_ILOCOS_SUR" },
  { countryCode: "PH", code: "ISA", enumName: "PHILIPPINES_ISABELA" },
  { countryCode: "PH", code: "KAL", enumName: "PHILIPPINES_KALINGA" },
  { countryCode: "PH", code: "LAG", enumName: "PHILIPPINES_LAGUNA" },
  { countryCode: "PH", code: "LAN", enumName: "PHILIPPINES_LANAO_DEL_NORTE" },
  { countryCode: "PH", code: "LAS", enumName: "PHILIPPINES_LANAO_DEL_SUR" },
  { countryCode: "PH", code: "LEY", enumName: "PHILIPPINES_LEYTE" },
  { countryCode: "PH", code: "LUN", enumName: "PHILIPPINES_LA_UNION" },
  { countryCode: "PH", code: "MAD", enumName: "PHILIPPINES_MARINDUQUE" },
  { countryCode: "PH", code: "MGN", enumName: "PHILIPPINES_MAGUINDANAO_DEL_NORTE" },
  { countryCode: "PH", code: "MGS", enumName: "PHILIPPINES_MAGUINDANAO_DEL_SUR" },
  { countryCode: "PH", code: "MAS", enumName: "PHILIPPINES_MASBATE" },
  { countryCode: "PH", code: "MDC", enumName: "PHILIPPINES_OCCIDENTAL_MINDORO" },
  { countryCode: "PH", code: "MDR", enumName: "PHILIPPINES_ORIENTAL_MINDORO" },
  { countryCode: "PH", code: "MOU", enumName: "PHILIPPINES_MOUNTAIN_PROVINCE" },
  { countryCode: "PH", code: "MSC", enumName: "PHILIPPINES_MISAMIS_OCCIDENTAL" },
  { countryCode: "PH", code: "MSR", enumName: "PHILIPPINES_MISAMIS_ORIENTAL" },
  { countryCode: "PH", code: "NCO", enumName: "PHILIPPINES_COTABATO" },
  { countryCode: "PH", code: "NEC", enumName: "PHILIPPINES_NEGROS_OCCIDENTAL" },
  { countryCode: "PH", code: "NER", enumName: "PHILIPPINES_NEGROS_ORIENTAL" },
  { countryCode: "PH", code: "NSA", enumName: "PHILIPPINES_NORTHERN_SAMAR" },
  { countryCode: "PH", code: "NUE", enumName: "PHILIPPINES_NUEVA_ECIJA" },
  { countryCode: "PH", code: "NUV", enumName: "PHILIPPINES_NUEVA_VIZCAYA" },
  { countryCode: "PH", code: "PAM", enumName: "PHILIPPINES_PAMPANGA" },
  { countryCode: "PH", code: "PAN", enumName: "PHILIPPINES_PANGASINAN" },
  { countryCode: "PH", code: "PLW", enumName: "PHILIPPINES_PALAWAN" },
  { countryCode: "PH", code: "QUE", enumName: "PHILIPPINES_QUEZON" },
  { countryCode: "PH", code: "QUI", enumName: "PHILIPPINES_QUIRINO" },
  { countryCode: "PH", code: "RIZ", enumName: "PHILIPPINES_RIZAL" },
  { countryCode: "PH", code: "ROM", enumName: "PHILIPPINES_ROMBLON" },
  { countryCode: "PH", code: "SAR", enumName: "PHILIPPINES_SARANGANI" },
  { countryCode: "PH", code: "SCO", enumName: "PHILIPPINES_SOUTH_COTABATO" },
  { countryCode: "PH", code: "SIG", enumName: "PHILIPPINES_SIQUIJOR" },
  { countryCode: "PH", code: "SLE", enumName: "PHILIPPINES_SOUTHERN_LEYTE" },
  { countryCode: "PH", code: "SLU", enumName: "PHILIPPINES_SULU" },
  { countryCode: "PH", code: "SOR", enumName: "PHILIPPINES_SORSOGON" },
  { countryCode: "PH", code: "SUK", enumName: "PHILIPPINES_SULTAN_KUDARAT" },
  { countryCode: "PH", code: "SUN", enumName: "PHILIPPINES_SURIGAO_DEL_NORTE" },
  { countryCode: "PH", code: "SUR", enumName: "PHILIPPINES_SURIGAO_DEL_SUR" },
  { countryCode: "PH", code: "TAR", enumName: "PHILIPPINES_TARLAC" },
  { countryCode: "PH", code: "TAW", enumName: "PHILIPPINES_TAWI_TAWI" },
  { countryCode: "PH", code: "WSA", enumName: "PHILIPPINES_SAMAR" },
  { countryCode: "PH", code: "ZAN", enumName: "PHILIPPINES_ZAMBOANGA_DEL_NORTE" },
  { countryCode: "PH", code: "ZAS", enumName: "PHILIPPINES_ZAMBOANGA_DEL_SUR" },
  { countryCode: "PH", code: "ZMB", enumName: "PHILIPPINES_ZAMBALES" },
  { countryCode: "PH", code: "ZSI", enumName: "PHILIPPINES_ZAMBOANGA_SIBUGAY" },
  { countryCode: "VN", code: "44", enumName: "VIET_NAM_AN_GIANG" },
  { countryCode: "VN", code: "43", enumName: "VIET_NAM_BA_RIA_VUNG_TAU" },
  { countryCode: "VN", code: "54", enumName: "VIET_NAM_BAC_GIANG" },
  { countryCode: "VN", code: "53", enumName: "VIET_NAM_BAC_KAN" },
  { countryCode: "VN", code: "55", enumName: "VIET_NAM_BAC_LIEU" },
  { countryCode: "VN", code: "56", enumName: "VIET_NAM_BAC_NINH" },
  { countryCode: "VN", code: "50", enumName: "VIET_NAM_BEN_TRE" },
  { countryCode: "VN", code: "31", enumName: "VIET_NAM_BINH_DINH" },
  { countryCode: "VN", code: "57", enumName: "VIET_NAM_BINH_DUONG" },
  { countryCode: "VN", code: "58", enumName: "VIET_NAM_BINH_PHUOC" },
  { countryCode: "VN", code: "40", enumName: "VIET_NAM_BINH_THUAN" },
  { countryCode: "VN", code: "59", enumName: "VIET_NAM_CA_MAU" },
  { countryCode: "VN", code: "CT", enumName: "VIET_NAM_CAN_THO" },
  { countryCode: "VN", code: "04", enumName: "VIET_NAM_CAO_BANG" },
  { countryCode: "VN", code: "DN", enumName: "VIET_NAM_DA_NANG" },
  { countryCode: "VN", code: "33", enumName: "VIET_NAM_DAK_LAK" },
  { countryCode: "VN", code: "72", enumName: "VIET_NAM_DAK_NONG" },
  { countryCode: "VN", code: "71", enumName: "VIET_NAM_DIEN_BIEN" },
  { countryCode: "VN", code: "39", enumName: "VIET_NAM_DONG_NAI" },
  { countryCode: "VN", code: "45", enumName: "VIET_NAM_DONG_THAP" },
  { countryCode: "VN", code: "30", enumName: "VIET_NAM_GIA_LAI" },
  { countryCode: "VN", code: "03", enumName: "VIET_NAM_HA_GIANG" },
  { countryCode: "VN", code: "63", enumName: "VIET_NAM_HA_NAM" },
  { countryCode: "VN", code: "HN", enumName: "VIET_NAM_HA_NOI" },
  { countryCode: "VN", code: "23", enumName: "VIET_NAM_HA_TINH" },
  { countryCode: "VN", code: "61", enumName: "VIET_NAM_HAI_DUONG" },
  { countryCode: "VN", code: "HP", enumName: "VIET_NAM_HAI_PHONG" },
  { countryCode: "VN", code: "73", enumName: "VIET_NAM_HAU_GIANG" },
  { countryCode: "VN", code: "SG", enumName: "VIET_NAM_HO_CHI_MINH" },
  { countryCode: "VN", code: "14", enumName: "VIET_NAM_HOA_BINH" },
  { countryCode: "VN", code: "66", enumName: "VIET_NAM_HUNG_YEN" },
  { countryCode: "VN", code: "34", enumName: "VIET_NAM_KHANH_HOA" },
  { countryCode: "VN", code: "47", enumName: "VIET_NAM_KIEN_GIANG" },
  { countryCode: "VN", code: "28", enumName: "VIET_NAM_KON_TUM" },
  { countryCode: "VN", code: "01", enumName: "VIET_NAM_LAI_CHAU" },
  { countryCode: "VN", code: "35", enumName: "VIET_NAM_LAM_DONG" },
  { countryCode: "VN", code: "09", enumName: "VIET_NAM_LANG_SON" },
  { countryCode: "VN", code: "02", enumName: "VIET_NAM_LAO_CAI" },
  { countryCode: "VN", code: "41", enumName: "VIET_NAM_LONG_AN" },
  { countryCode: "VN", code: "67", enumName: "VIET_NAM_NAM_DINH" },
  { countryCode: "VN", code: "22", enumName: "VIET_NAM_NGHE_AN" },
  { countryCode: "VN", code: "18", enumName: "VIET_NAM_NINH_BINH" },
  { countryCode: "VN", code: "36", enumName: "VIET_NAM_NINH_THUAN" },
  { countryCode: "VN", code: "68", enumName: "VIET_NAM_PHU_THO" },
  { countryCode: "VN", code: "32", enumName: "VIET_NAM_PHU_YEN" },
  { countryCode: "VN", code: "24", enumName: "VIET_NAM_QUANG_BINH" },
  { countryCode: "VN", code: "27", enumName: "VIET_NAM_QUANG_NAM" },
  { countryCode: "VN", code: "29", enumName: "VIET_NAM_QUANG_NGAI" },
  { countryCode: "VN", code: "13", enumName: "VIET_NAM_QUANG_NINH" },
  { countryCode: "VN", code: "25", enumName: "VIET_NAM_QUANG_TRI" },
  { countryCode: "VN", code: "52", enumName: "VIET_NAM_SOC_TRANG" },
  { countryCode: "VN", code: "05", enumName: "VIET_NAM_SON_LA" },
  { countryCode: "VN", code: "37", enumName: "VIET_NAM_TAY_NINH" },
  { countryCode: "VN", code: "20", enumName: "VIET_NAM_THAI_BINH" },
  { countryCode: "VN", code: "69", enumName: "VIET_NAM_THAI_NGUYEN" },
  { countryCode: "VN", code: "21", enumName: "VIET_NAM_THANH_HOA" },
  { countryCode: "VN", code: "26", enumName: "VIET_NAM_THUA_THIEN_HUE" },
  { countryCode: "VN", code: "46", enumName: "VIET_NAM_TIEN_GIANG" },
  { countryCode: "VN", code: "51", enumName: "VIET_NAM_TRA_VINH" },
  { countryCode: "VN", code: "07", enumName: "VIET_NAM_TUYEN_QUANG" },
  { countryCode: "VN", code: "49", enumName: "VIET_NAM_VINH_LONG" },
  { countryCode: "VN", code: "70", enumName: "VIET_NAM_VINH_PHUC" },
  { countryCode: "VN", code: "06", enumName: "VIET_NAM_YEN_BAI" },
] satisfies AdministrativeAreaOption[];

const enumCountryPrefixes: Record<string, string> = {
  AU: "AUSTRALIA_",
  CA: "CANADA_",
  CN: "CHINA_",
  JP: "JAPAN_",
  KR: "KOREA_",
  NZ: "NEW_ZEALAND_",
  PH: "PHILIPPINES_",
  TH: "THAILAND_",
  TW: "TAIWAN_",
  US: "UNITED_STATES_",
  VN: "VIET_NAM_",
};

const supportedCountryCodes = new Set(countryCodes);

export const isCountryCodeOption = (value: string): value is CountryCodeOption =>
  supportedCountryCodes.has(value as CountryCodeOption);

export const getCountryLabel = (countryCode: CountryCodeOption, locale: Locale): string => {
  const displayName = new Intl.DisplayNames([locale], { type: "region" }).of(countryCode);

  return displayName ? `${displayName} (${countryCode})` : countryCode;
};

const titleCaseAdministrativeArea = (enumName: string, countryCode: CountryCodeOption): string => {
  const prefix = enumCountryPrefixes[countryCode] ?? "";
  const labelSource = enumName.startsWith(prefix) ? enumName.slice(prefix.length) : enumName;

  return labelSource
    .split("_")
    .map((segment) => segment.charAt(0) + segment.slice(1).toLowerCase())
    .join(" ");
};

export const getAdministrativeAreaOptions = (countryCode: string, locale: Locale) => {
  if (!isCountryCodeOption(countryCode)) {
    return [];
  }

  return administrativeAreaOptions
    .filter((option) => option.countryCode === countryCode)
    .map((option) => {
      const fullCode = `${option.countryCode}-${option.code}`;
      const fallbackLabel = titleCaseAdministrativeArea(option.enumName, option.countryCode);

      return {
        code: option.code,
        label: getLocalizedAdministrativeAreaLabel(fullCode, locale, fallbackLabel),
      };
    });
};

export const isAdministrativeAreaSupportedByCountry = (countryCode: string, administrativeAreaCode: string): boolean =>
  isCountryCodeOption(countryCode) &&
  administrativeAreaOptions.some((option) =>
    option.countryCode === countryCode &&
    option.code === administrativeAreaCode);
